BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Log] ADD [authorId] INT,
[createdAt] DATETIME2 NOT NULL CONSTRAINT [Log_createdAt_df] DEFAULT CURRENT_TIMESTAMP;

-- AddForeignKey
ALTER TABLE [dbo].[Log] ADD CONSTRAINT [Log_authorId_fkey] FOREIGN KEY ([authorId]) REFERENCES [dbo].[User]([id]) ON DELETE SET NULL ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
