import "./globals.css";
import { Merriweather } from "next/font/google";
import QueryWrapper from "./components/QueryWrapper";

export const metadata = {
  title: "Sql Project",
  description: "Generated by create next app",
};

const font = Merriweather({
  weight: ["400", "700", "900"],
  subsets: ["latin"],
  variable: "--font-merriweather",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>
        <QueryWrapper>{children}</QueryWrapper>
      </body>
    </html>
  );
}
